### PR TITLE
Plots

### PR DESCRIPTION
**Pull request by lindavdboogaart**
Saved the plots from data_prep.Rmd and regression_analysis.Rmd as pdf files. Also included some of these plots in the paper.Rmd.

@Ciertje saving this plots included creating some directories.

Furthermore, it is important to check at a later point whether all the path files in code work correctly. For example, in getting_the_data.R I could use "data/", whereas in the other documents I had to use "../../data" although my working directory was constantly set to the root directory of the repository.

### CODE REVIEW

**Comment by Ciertje** [comment]
so i was looking at your code but I am struggling a little to understand what is happening? you only call the plots? or where are they generated? did you save the plots seperately and then called them (is there than a seperate file somewhere?)

**Comment by lindavdboogaart** [comment]
@Ciertje I saved all the plots that are created in the data_prep.Rmd and regression_analysis.Rmd. For that I used the ggsave commands in those files. With those commands I stored the plots as pdf files in gen/data_prep/output/figure and gen/analysis/output/figure. (I also used dir.create in the code files to create these folders). In the paper.Rmd I then attach these pdf's of the plots using knitr::include_graphics.

**Comment by Ciertje** [comment]
I saw some graphs that you missed. Because i was working on a another document i copied you code chunks and integrated them. I hope you don't mind

**Comment by lindavdboogaart** [comment]
That's fine

**Comment by Ciertje** [comment]
all your modifications were included in the branch merge "finishing_touch".  Great work!

**Pull request closed without merging**
